### ISSUE TITLE
How different is this method from loading the posts from componentDidMount?

### ISSUE THREAD

**Issue by THPubs** [sergiodxa/react-wordpress#1]
Hi,

First, thanks a lot for this sample code. It really helped. I just did some experiments with it. You wrote the ajax call on the server side. Can you please explain what's happening there and how it effects SEO?

**Comment by sergiodxa** [comment]
Did you know Next.js? This example app use it to server-render the React app, that's way I did the HTTP request in the server. The SEO it's not a problem because you are serving the content from the server. BTW Google can index content rendered in the client with JS without any problem.

**Comment by THPubs** [comment]
@sergiodxa Great thanks! Sorry I'm new to Next. :smile:
